"""Initial schema

Revision ID: 4f94303945df
Revises: 
Create Date: 2025-12-30 09:03:53.165237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f94303945df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('connected_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(length=20), nullable=False),
    sa.Column('login_customer_id', sa.String(length=20), nullable=True),
    sa.Column('descriptive_name', sa.String(length=255), nullable=True),
    sa.Column('currency_code', sa.String(length=10), nullable=True),
    sa.Column('time_zone', sa.String(length=50), nullable=True),
    sa.Column('encrypted_refresh_token', sa.Text(), nullable=False),
    sa.Column('encrypted_access_token', sa.Text(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'PARTIAL', name='syncstatus'), nullable=True),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'customer_id', name='uq_user_customer')
    )
    op.create_index(op.f('ix_connected_accounts_customer_id'), 'connected_accounts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_connected_accounts_id'), 'connected_accounts', ['id'], unique=False)
    op.create_index('ix_connected_accounts_user_customer', 'connected_accounts', ['user_id', 'customer_id'], unique=False)
    op.create_index(op.f('ix_connected_accounts_user_id'), 'connected_accounts', ['user_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('advertising_channel_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['connected_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'campaign_id', name='uq_account_campaign')
    )
    op.create_index('ix_campaigns_account_campaign', 'campaigns', ['account_id', 'campaign_id'], unique=False)
    op.create_index(op.f('ix_campaigns_account_id'), 'campaigns', ['account_id'], unique=False)
    op.create_index(op.f('ix_campaigns_campaign_id'), 'campaigns', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.create_table('suggestion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('ads_processed', sa.Integer(), nullable=False),
    sa.Column('suggestions_generated', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['connected_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suggestion_runs_account_id'), 'suggestion_runs', ['account_id'], unique=False)
    op.create_index(op.f('ix_suggestion_runs_created_at'), 'suggestion_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_suggestion_runs_id'), 'suggestion_runs', ['id'], unique=False)
    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'PARTIAL', name='syncstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('ads_synced', sa.Integer(), nullable=False),
    sa.Column('campaigns_synced', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['connected_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_runs_account_id'), 'sync_runs', ['account_id'], unique=False)
    op.create_index(op.f('ix_sync_runs_celery_task_id'), 'sync_runs', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_sync_runs_created_at'), 'sync_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_sync_runs_id'), 'sync_runs', ['id'], unique=False)
    op.create_index(op.f('ix_sync_runs_status'), 'sync_runs', ['status'], unique=False)
    op.create_table('ad_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('ad_group_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_groups_ad_group_id'), 'ad_groups', ['ad_group_id'], unique=False)
    op.create_index(op.f('ix_ad_groups_campaign_id'), 'ad_groups', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_ad_groups_id'), 'ad_groups', ['id'], unique=False)
    op.create_table('ads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_group_id', sa.Integer(), nullable=False),
    sa.Column('ad_id', sa.String(length=50), nullable=False),
    sa.Column('ad_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('headlines', sa.JSON(), nullable=True),
    sa.Column('descriptions', sa.JSON(), nullable=True),
    sa.Column('final_urls', sa.JSON(), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('bucket', sa.Enum('BEST', 'WORST', 'UNKNOWN', name='adbucket'), nullable=True),
    sa.Column('bucket_score', sa.Float(), nullable=True),
    sa.Column('bucket_explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ad_group_id'], ['ad_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ads_ad_group_id'), 'ads', ['ad_group_id'], unique=False)
    op.create_index(op.f('ix_ads_ad_id'), 'ads', ['ad_id'], unique=True)
    op.create_index(op.f('ix_ads_bucket'), 'ads', ['bucket'], unique=False)
    op.create_index(op.f('ix_ads_id'), 'ads', ['id'], unique=False)
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_group_id', sa.Integer(), nullable=False),
    sa.Column('criterion_id', sa.String(length=50), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('match_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ad_group_id'], ['ad_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ad_group_id', 'criterion_id', name='uq_adgroup_criterion')
    )
    op.create_index(op.f('ix_keywords_ad_group_id'), 'keywords', ['ad_group_id'], unique=False)
    op.create_index(op.f('ix_keywords_criterion_id'), 'keywords', ['criterion_id'], unique=False)
    op.create_index(op.f('ix_keywords_id'), 'keywords', ['id'], unique=False)
    op.create_table('ad_metrics_90d',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_id', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.BigInteger(), nullable=False),
    sa.Column('clicks', sa.BigInteger(), nullable=False),
    sa.Column('cost_micros', sa.BigInteger(), nullable=False),
    sa.Column('conversions', sa.Float(), nullable=False),
    sa.Column('all_conversions', sa.Float(), nullable=False),
    sa.Column('ctr', sa.Float(), nullable=True),
    sa.Column('average_cpc', sa.Float(), nullable=True),
    sa.Column('cost_per_conversion', sa.Float(), nullable=True),
    sa.Column('conversion_rate', sa.Float(), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_metrics_90d_ad_id'), 'ad_metrics_90d', ['ad_id'], unique=True)
    op.create_index(op.f('ix_ad_metrics_90d_id'), 'ad_metrics_90d', ['id'], unique=False)
    op.create_table('ad_metrics_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('impressions', sa.BigInteger(), nullable=False),
    sa.Column('clicks', sa.BigInteger(), nullable=False),
    sa.Column('cost_micros', sa.BigInteger(), nullable=False),
    sa.Column('conversions', sa.Float(), nullable=False),
    sa.Column('all_conversions', sa.Float(), nullable=False),
    sa.Column('ctr', sa.Float(), nullable=True),
    sa.Column('average_cpc', sa.Float(), nullable=True),
    sa.Column('cost_per_conversion', sa.Float(), nullable=True),
    sa.Column('conversion_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ad_id', 'date', name='uq_ad_date')
    )
    op.create_index('ix_ad_metrics_daily_ad_date', 'ad_metrics_daily', ['ad_id', 'date'], unique=False)
    op.create_index(op.f('ix_ad_metrics_daily_ad_id'), 'ad_metrics_daily', ['ad_id'], unique=False)
    op.create_index(op.f('ix_ad_metrics_daily_date'), 'ad_metrics_daily', ['date'], unique=False)
    op.create_index(op.f('ix_ad_metrics_daily_id'), 'ad_metrics_daily', ['id'], unique=False)
    op.create_table('suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_id', sa.Integer(), nullable=False),
    sa.Column('suggestion_run_id', sa.Integer(), nullable=False),
    sa.Column('headlines', sa.JSON(), nullable=False),
    sa.Column('descriptions', sa.JSON(), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('exemplar_ad_ids', sa.JSON(), nullable=False),
    sa.Column('similarity_scores', sa.JSON(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('applied_ad_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], ),
    sa.ForeignKeyConstraint(['suggestion_run_id'], ['suggestion_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suggestions_ad_id'), 'suggestions', ['ad_id'], unique=False)
    op.create_index(op.f('ix_suggestions_created_at'), 'suggestions', ['created_at'], unique=False)
    op.create_index(op.f('ix_suggestions_id'), 'suggestions', ['id'], unique=False)
    op.create_index(op.f('ix_suggestions_suggestion_run_id'), 'suggestions', ['suggestion_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suggestions_suggestion_run_id'), table_name='suggestions')
    op.drop_index(op.f('ix_suggestions_id'), table_name='suggestions')
    op.drop_index(op.f('ix_suggestions_created_at'), table_name='suggestions')
    op.drop_index(op.f('ix_suggestions_ad_id'), table_name='suggestions')
    op.drop_table('suggestions')
    op.drop_index(op.f('ix_ad_metrics_daily_id'), table_name='ad_metrics_daily')
    op.drop_index(op.f('ix_ad_metrics_daily_date'), table_name='ad_metrics_daily')
    op.drop_index(op.f('ix_ad_metrics_daily_ad_id'), table_name='ad_metrics_daily')
    op.drop_index('ix_ad_metrics_daily_ad_date', table_name='ad_metrics_daily')
    op.drop_table('ad_metrics_daily')
    op.drop_index(op.f('ix_ad_metrics_90d_id'), table_name='ad_metrics_90d')
    op.drop_index(op.f('ix_ad_metrics_90d_ad_id'), table_name='ad_metrics_90d')
    op.drop_table('ad_metrics_90d')
    op.drop_index(op.f('ix_keywords_id'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_criterion_id'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_ad_group_id'), table_name='keywords')
    op.drop_table('keywords')
    op.drop_index(op.f('ix_ads_id'), table_name='ads')
    op.drop_index(op.f('ix_ads_bucket'), table_name='ads')
    op.drop_index(op.f('ix_ads_ad_id'), table_name='ads')
    op.drop_index(op.f('ix_ads_ad_group_id'), table_name='ads')
    op.drop_table('ads')
    op.drop_index(op.f('ix_ad_groups_id'), table_name='ad_groups')
    op.drop_index(op.f('ix_ad_groups_campaign_id'), table_name='ad_groups')
    op.drop_index(op.f('ix_ad_groups_ad_group_id'), table_name='ad_groups')
    op.drop_table('ad_groups')
    op.drop_index(op.f('ix_sync_runs_status'), table_name='sync_runs')
    op.drop_index(op.f('ix_sync_runs_id'), table_name='sync_runs')
    op.drop_index(op.f('ix_sync_runs_created_at'), table_name='sync_runs')
    op.drop_index(op.f('ix_sync_runs_celery_task_id'), table_name='sync_runs')
    op.drop_index(op.f('ix_sync_runs_account_id'), table_name='sync_runs')
    op.drop_table('sync_runs')
    op.drop_index(op.f('ix_suggestion_runs_id'), table_name='suggestion_runs')
    op.drop_index(op.f('ix_suggestion_runs_created_at'), table_name='suggestion_runs')
    op.drop_index(op.f('ix_suggestion_runs_account_id'), table_name='suggestion_runs')
    op.drop_table('suggestion_runs')
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_campaign_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_account_id'), table_name='campaigns')
    op.drop_index('ix_campaigns_account_campaign', table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_connected_accounts_user_id'), table_name='connected_accounts')
    op.drop_index('ix_connected_accounts_user_customer', table_name='connected_accounts')
    op.drop_index(op.f('ix_connected_accounts_id'), table_name='connected_accounts')
    op.drop_index(op.f('ix_connected_accounts_customer_id'), table_name='connected_accounts')
    op.drop_table('connected_accounts')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
